In [14]:
import numpy as np
import pandas as pd

In [15]:
from sklearn.datasets import load_wine

In [16]:
wine = load_wine()
wine.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [17]:
X = pd.DataFrame(data=wine['data'],columns=wine['feature_names'])

In [18]:
y = pd.Series(data=wine['target'])

In [19]:
# split data
from sklearn.model_selection import train_test_split

In [20]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3)

In [21]:
from sklearn.ensemble import RandomForestClassifier

In [22]:
rfc = RandomForestClassifier(n_estimators=200)
rfc.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=200,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [23]:
prediction = rfc.predict(X_test)

In [24]:
prediction

array([1, 1, 2, 1, 1, 0, 0, 2, 1, 1, 1, 1, 1, 2, 2, 2, 0, 1, 2, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 2, 1, 0, 2, 0, 1, 2, 1, 1,
       1, 2, 1, 1, 0, 2, 1, 2, 0, 0])

In [25]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,prediction))

[[19  0  0]
 [ 1 22  1]
 [ 0  0 11]]


In [26]:
print(classification_report(y_test,prediction))

              precision    recall  f1-score   support

           0       0.95      1.00      0.97        19
           1       1.00      0.92      0.96        24
           2       0.92      1.00      0.96        11

    accuracy                           0.96        54
   macro avg       0.96      0.97      0.96        54
weighted avg       0.97      0.96      0.96        54

